const product = [
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 139000,
    show: true,
    active: true,
    name: '나이키 에어 리프트 SE',
    quantity: 990,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_01.png`,
        name: 'NIKE_AIR_LIFT_SE_01.png',
        originalname: 'NIKE_AIR_LIFT_SE_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_02.png`,
        name: 'NIKE_AIR_LIFT_SE_02.png',
        originalname: 'NIKE_AIR_LIFT_SE_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_03.jpg`,
        name: 'NIKE_AIR_LIFT_SE_03.jpg',
        originalname: 'NIKE_AIR_LIFT_SE_03.jpg',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_04.jpg`,
        name: 'NIKE_AIR_LIFT_SE_04.jpg',
        originalname: 'NIKE_AIR_LIFT_SE_04.jpg',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_05.png`,
        name: 'NIKE_AIR_LIFT_SE_05.png',
        originalname: 'NIKE_AIR_LIFT_SE_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_06.jpg`,
        name: 'NIKE_AIR_LIFT_SE_06.jpg',
        originalname: 'NIKE_AIR_LIFT_SE_06.jpg',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_07.png`,
        name: 'NIKE_AIR_LIFT_SE_07.png',
        originalname: 'NIKE_AIR_LIFT_SE_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_08.png`,
        name: 'NIKE_AIR_LIFT_SE_08.png',
        originalname: 'NIKE_AIR_LIFT_SE_08.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_LIFT_SE_09.png`,
        name: 'NIKE_AIR_LIFT_SE_09.png',
        originalname: 'NIKE_AIR_LIFT_SE_09.png',
      },
    ],
    content: `1996년에 출시된 오리지널 에어 리프트를 한층 업그레이드한 이 스페셜 에디션은 내구성을 유지하면서도 섬세한 디자인을 구현한 아이템입니다. 토 부분이 트인 디자인이 균형감을 유지해 주며, 리본과 스트랩을 조절해 개성 있는 핏과 스타일을 연출할 수 있습니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      isNew: false,
      isBest: true,
      category: ['PC02', 'PC0201'], // Women > 용품
      size: [220, 230, 240, 250, 260, 270, 280, 290],
      color: '라이트 소프트 핑크/페일 아이보리/라이트 소프트 핑크',
      styleNo: 'HQ3761-640',
      primeCost: 139000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 159000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 에어 포스 1 댄스',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_01.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_01.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_01.png',
      },
    ],
    content: `원활한 동작 수행을 위해 탄생한 에어 포스 1입니다. 댄서의 니즈에 맞게 디자인된 이번 버전은 발 앞부분에 에어 쿠셔닝을 적용해 지지력을 조절할 수 있습니다. 윤곽을 살린 갑피와 두꺼워진 카라가 중족부와 뒤꿈치를 고정해 주며, 더욱 유연한 밑창 덕분에 풋워크를 쉽게 뽐낼 수 있습니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC02', 'PC0201'], // Women > 신발
      primeCost: 159000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 159000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 에어 포스 1 댄스',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_01.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_01.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_02.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_02.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_03.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_03.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_04.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_04.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_05.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_05.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_06.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_06.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_07.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_07.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_08.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_08.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_08.png',
      },
    ],
    content: `나이키 에어 포스 1 댄스 형광색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '볼트/건메탈/블랙',
      styleNo: 'FJ7409-700',
      primeCost: 159000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 159000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 에어 포스 1 댄스',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_01.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_01.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_02.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_02.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_03.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_03.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_04.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_04.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_05.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_05.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_06.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_06.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_b_07.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_b_07.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_b_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_08.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_08.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_08.png',
      },
    ],
    content: `나이키 에어 포스 1 댄스 하얀색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '화이트/화이트/메탈릭 실버/화이트',
      styleNo: 'FJ7409-100',
      primeCost: 159000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 159000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 에어 포스 1 댄스',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_01.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_01.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_02.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_02.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_03.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_03.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_04.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_04.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_05.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_05.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_06.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_06.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_07.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_07.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_1_DANCE_c_08.png`,
        name: 'NIKE_AIR_FORCE_1_DANCE_c_08.png',
        originalname: 'NIKE_AIR_FORCE_1_DANCE_c_08.png',
      },
    ],
    content: `나이키 에어 포스 1 댄스 실버색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '서밋 화이트/포톤 더스트/메탈릭 실버',
      styleNo: 'FJ7409-101',
      primeCost: 159000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 179000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 메트콘 9 AMP',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_METCON_01.png`,
        name: 'NIKE_METCON_01.png',
        originalname: 'NIKE_METCON_01.png',
      },
    ],
    content: `운동을 하는 '이유'가 무엇이든, 메트콘 9는 그럴 만한 가치가 있게 만들어 줍니다. 더욱 커진 하이퍼리프트 플레이트와 추가된 고무 로프 랩으로 메트콘 8을 개선했습니다. 리프터와 크로스 트레이너 및 투지가 강한 이들을 위해 제작되었으며 세계 최고의 운동선수들의 신뢰를 받고 있는 이 신발은 여전히 매일같이 기대에 부응하는, 모범과도 같은 제품입니다. 비타민에서 영감을 받은 이 밸런스 좋은 디자인으로 운동을 할 때도, 사람들을 만날 때도 활기찬 에너지를 발산해 보세요.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC02', 'PC0201'], // Women > 신발
      primeCost: 179000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 179000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 메트콘 9 AMP',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_METCON_01.png`,
        name: 'NIKE_METCON_01.png',
        originalname: 'NIKE_METCON_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_02.png`,
        name: 'NIKE_METCON_02.png',
        originalname: 'NIKE_METCON_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_03.png`,
        name: 'NIKE_METCON_03.png',
        originalname: 'NIKE_METCON_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_04.png`,
        name: 'NIKE_METCON_04.png',
        originalname: 'NIKE_METCON_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_05.png`,
        name: 'NIKE_METCON_05.png',
        originalname: 'NIKE_METCON_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_06.png`,
        name: 'NIKE_METCON_06.png',
        originalname: 'NIKE_METCON_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_07.png`,
        name: 'NIKE_METCON_07.png',
        originalname: 'NIKE_METCON_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_08.png`,
        name: 'NIKE_METCON_08.png',
        originalname: 'NIKE_METCON_08.png',
      },
    ],
    content: `나이키 메트콘 9 AMP 오렌지색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '화이트/라이트 본/라임스톤/미드나이트 네이비',
      styleNo: 'DZ2539-100',
      primeCost: 179000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 179000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 메트콘 9 AMP',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_METCON_b_01.jpeg`,
        name: 'NIKE_METCON_b_01.jpeg',
        originalname: 'NIKE_METCON_b_01.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_02.png`,
        name: 'NIKE_METCON_b_02.png',
        originalname: 'NIKE_METCON_b_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_03.jpeg`,
        name: 'NIKE_METCON_b_03.jpeg',
        originalname: 'NIKE_METCON_b_03.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_04.jpeg`,
        name: 'NIKE_METCON_b_04.jpeg',
        originalname: 'NIKE_METCON_b_04.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_05.jpeg`,
        name: 'NIKE_METCON_b_05.jpeg',
        originalname: 'NIKE_METCON_b_05.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_06.png`,
        name: 'NIKE_METCON_b_06.png',
        originalname: 'NIKE_METCON_b_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_07.jpeg`,
        name: 'NIKE_METCON_b_07.jpeg',
        originalname: 'NIKE_METCON_b_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_METCON_b_08.jpeg`,
        name: 'NIKE_METCON_b_08.jpeg',
        originalname: 'NIKE_METCON_b_08.jpeg',
      },
    ],
    content: `나이키 메트콘 9 AMP 버건디색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '버건디 크러시/다크 비트루트/러시 핑크/블랙',
      styleNo: 'DZ2539-600',
      primeCost: 179000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 219000,
    show: true,
    active: true,
    name: '나이키 에어맥스 플라이니트 벤처',
    quantity: 990,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_01.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_01.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_02.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_02.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_03.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_03.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_04.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_04.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_05.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_05.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_06.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_06.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_07.jpeg`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_07.jpeg',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_AIRMAX_FLYKNIT_VENTURE_08.png`,
        name: 'NIKE_AIRMAX_FLYKNIT_VENTURE_08.png',
        originalname: 'NIKE_AIRMAX_FLYKNIT_VENTURE_08.png',
      },
    ],
    content: `아웃도어에서 영감을 받아 유틸리티 스타일로 완성된 벤처를 만나보세요. 기능적 디테일과 청키한 룩이 거친 감성을 선사하며, 커스텀이 가능한 끈 조임 시스템은 착화감을 개선하여 도시의 보도와 트레일을 편안하게 달릴 수 있습니다. 무한한 가능성을 누려보세요.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      isNew: false,
      isBest: true,
      category: ['PC02', 'PC0201'], // Women > 용품
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '씨 글래스/파슬/플래티넘 바이올렛/문 파슬',
      styleNo: 'FD2110-003',
      primeCost: 219000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 79000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 버로우 SE',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_BOROUGH_01.png`,
        name: 'NIKE_BOROUGH_01.png',
        originalname: 'NIKE_BOROUGH_01.png',
      },
    ],
    content: `어디를 가든 포근함을 느껴보세요. 플리스 느낌의 안감이따뜻함을 유지해 주고, 마시멜로처럼 부드러운 폼 중창과 밑창, 그립감 있는 접지 패턴이 걸을 때마다 탄성감을 선사합니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC02', 'PC0201'], // Women > 신발
      primeCost: 79000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 79000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 버로우 SE',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_BOROUGH_01.png`,
        name: 'NIKE_BOROUGH_01.png',
        originalname: 'NIKE_BOROUGH_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_02.png`,
        name: 'NIKE_BOROUGH_02.png',
        originalname: 'NIKE_BOROUGH_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_03.png`,
        name: 'NIKE_BOROUGH_03.png',
        originalname: 'NIKE_BOROUGH_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_04.png`,
        name: 'NIKE_BOROUGH_04.png',
        originalname: 'NIKE_BOROUGH_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_05.png`,
        name: 'NIKE_BOROUGH_05.png',
        originalname: 'NIKE_BOROUGH_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_06.png`,
        name: 'NIKE_BOROUGH_06.png',
        originalname: 'NIKE_BOROUGH_06.png',
      },
    ],
    content: `나이키 버로우 SE 검은색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 230, 240, 250, 260],
      color: '블랙/블랙',
      styleNo: 'FZ7939-001',
      primeCost: 79000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 79000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 버로우 SE',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_BOROUGH_b_01.png`,
        name: 'NIKE_BOROUGH_b_01.png',
        originalname: 'NIKE_BOROUGH_b_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_b_02.png`,
        name: 'NIKE_BOROUGH_b_02.png',
        originalname: 'NIKE_BOROUGH_b_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_b_03.png`,
        name: 'NIKE_BOROUGH_b_03.png',
        originalname: 'NIKE_BOROUGH_b_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_b_04.png`,
        name: 'NIKE_BOROUGH_b_04.png',
        originalname: 'NIKE_BOROUGH_b_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_b_05.png`,
        name: 'NIKE_BOROUGH_b_05.png',
        originalname: 'NIKE_BOROUGH_b_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_b_06.png`,
        name: 'NIKE_BOROUGH_b_06.png',
        originalname: 'NIKE_BOROUGH_b_06.png',
      },
    ],
    content: `나이키 버로우 SE 실버색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 230, 240, 250, 260],
      color: '메탈릭 실버/라이트 오어우드 브라운',
      styleNo: 'FZ7939-002',
      primeCost: 79000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 79000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 버로우 SE',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_BOROUGH__c01.png`,
        name: 'NIKE_BOROUGH_c_01.png',
        originalname: 'NIKE_BOROUGH_c_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_c_02.png`,
        name: 'NIKE_BOROUGH_c_02.png',
        originalname: 'NIKE_BOROUGH_c_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_c_03.png`,
        name: 'NIKE_BOROUGH_c_03.png',
        originalname: 'NIKE_BOROUGH_c_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_c_04.png`,
        name: 'NIKE_BOROUGH_c_04.png',
        originalname: 'NIKE_BOROUGH_c_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_c_05.png`,
        name: 'NIKE_BOROUGH_c_05.png',
        originalname: 'NIKE_BOROUGH_c_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_BOROUGH_c_06.png`,
        name: 'NIKE_BOROUGH_c_06.png',
        originalname: 'NIKE_BOROUGH_c_06.png',
      },
    ],
    content: `나이키 버로우 SE 바이올렛색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 230, 240, 250, 260],
      color: '라이트 바이올렛 오어/라이트 바이올렛 오어',
      styleNo: 'FZ7939-200',
      primeCost: 79000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 219000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 제가마 2',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_01.png`,
        name: 'NIKE_ZEGAMA_01.png',
        originalname: 'NIKE_ZEGAMA_01.png',
      },
    ],
    content: `산에 오르고 숲을 지나 트레일 끝까지 갈 수 있습니다. 반응성이 매우 뛰어난 줌X 폼 중창이 장착된 제가마 2는 가파른 능선, 들쭉날쭉한 바위를 넘고 트레일의 시작부터 끝까지 나아갈 수 있도록 설계되었습니다. 최적의 쿠셔닝이 트레일 러닝용으로 제작된 울퉁불퉁한 밑창을 보완해 줍니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC02', 'PC0201'], // Women > 신발
      primeCost: 219000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 219000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 제가마 2',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_01.png`,
        name: 'NIKE_ZEGAMA_01.png',
        originalname: 'NIKE_ZEGAMA_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_02.png`,
        name: 'NIKE_ZEGAMA_02.png',
        originalname: 'NIKE_ZEGAMA_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_03.png`,
        name: 'NIKE_ZEGAMA_03.png',
        originalname: 'NIKE_ZEGAMA_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_04.png`,
        name: 'NIKE_ZEGAMA_04.png',
        originalname: 'NIKE_ZEGAMA_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_05.png`,
        name: 'NIKE_ZEGAMA_05.png',
        originalname: 'NIKE_ZEGAMA_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_06.png`,
        name: 'NIKE_ZEGAMA_06.png',
        originalname: 'NIKE_ZEGAMA_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_07.jpeg`,
        name: 'NIKE_ZEGAMA_07.jpeg',
        originalname: 'NIKE_ZEGAMA_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_08.jpeg`,
        name: 'NIKE_ZEGAMA_08.jpeg',
        originalname: 'NIKE_ZEGAMA_08.jpeg',
      },
    ],
    content: `나이키 제가마 2 검은색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '블랙/메탈릭 플래티넘/앤트러사이트',
      styleNo: 'FD5191-003',
      primeCost: 219000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 219000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 제가마 2',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_01.png`,
        name: 'NIKE_ZEGAMA_b_01.png',
        originalname: 'NIKE_ZEGAMA_b_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_02.png`,
        name: 'NIKE_ZEGAMA_b_02.png',
        originalname: 'NIKE_ZEGAMA_b_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_03.png`,
        name: 'NIKE_ZEGAMA_b_03.png',
        originalname: 'NIKE_ZEGAMA_b_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_04.jpeg`,
        name: 'NIKE_ZEGAMA_b_04.jpeg',
        originalname: 'NIKE_ZEGAMA_b_04.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_05.png`,
        name: 'NIKE_ZEGAMA_b_05.png',
        originalname: 'NIKE_ZEGAMA_b_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_06.png`,
        name: 'NIKE_ZEGAMA_b_06.png',
        originalname: 'NIKE_ZEGAMA_b_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_07.jpeg`,
        name: 'NIKE_ZEGAMA_b_07.jpeg',
        originalname: 'NIKE_ZEGAMA_b_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_b_08.jpeg`,
        name: 'NIKE_ZEGAMA_b_08.jpeg',
        originalname: 'NIKE_ZEGAMA_b_08.jpeg',
      },
    ],
    content: `나이키 제가마 2 초록색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '제이드 호라이즌/사이버/크림슨 틴트/세일',
      styleNo: 'FD5191-300',
      primeCost: 219000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 219000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 제가마 2',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_01.png`,
        name: 'NIKE_ZEGAMA_c_01.png',
        originalname: 'NIKE_ZEGAMA_c_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_02.png`,
        name: 'NIKE_ZEGAMA_c_02.png',
        originalname: 'NIKE_ZEGAMA_c_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_03.png`,
        name: 'NIKE_ZEGAMA_c_03.png',
        originalname: 'NIKE_ZEGAMA_c_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_04.png`,
        name: 'NIKE_ZEGAMA_c_04.png',
        originalname: 'NIKE_ZEGAMA_c_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_05.png`,
        name: 'NIKE_ZEGAMA_c_05.png',
        originalname: 'NIKE_ZEGAMA_c_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_06.png`,
        name: 'NIKE_ZEGAMA_c_06.png',
        originalname: 'NIKE_ZEGAMA_c_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_07.jpeg`,
        name: 'NIKE_ZEGAMA_c_07.jpeg',
        originalname: 'NIKE_ZEGAMA_c_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_c_08.jpeg`,
        name: 'NIKE_ZEGAMA_c_08.jpeg',
        originalname: 'NIKE_ZEGAMA_c_08.jpeg',
      },
    ],
    content: `나이키 제가마 2 남색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '아머리 네이비/셀레스티얼 골드/빈티지 그린/메탈릭 실버',
      styleNo: 'FD5191-401',
      primeCost: 219000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 197000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 제가마 2',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_01.png`,
        name: 'NIKE_ZEGAMA_d_01.png',
        originalname: 'NIKE_ZEGAMA_d_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_02.png`,
        name: 'NIKE_ZEGAMA_d_02.png',
        originalname: 'NIKE_ZEGAMA_d_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_03.png`,
        name: 'NIKE_ZEGAMA_d_03.png',
        originalname: 'NIKE_ZEGAMA_d_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_04.png`,
        name: 'NIKE_ZEGAMA_d_04.png',
        originalname: 'NIKE_ZEGAMA_d_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_05.png`,
        name: 'NIKE_ZEGAMA_d_05.png',
        originalname: 'NIKE_ZEGAMA_d_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_06.png`,
        name: 'NIKE_ZEGAMA_d_06.png',
        originalname: 'NIKE_ZEGAMA_d_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_07.jpeg`,
        name: 'NIKE_ZEGAMA_d_07.jpeg',
        originalname: 'NIKE_ZEGAMA_d_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZEGAMA_d_08.jpeg`,
        name: 'NIKE_ZEGAMA_d_08.jpeg',
        originalname: 'NIKE_ZEGAMA_d_08.jpeg',
      },
    ],
    content: `나이키 제가마 2 회색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '블랙/울프 그레이/앤트러사이트/화이트',
      styleNo: 'FD5191-001',
      primeCost: 219000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 209000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이이키 페가수스 트레일 5 GORE-TEX',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_PEGASUS_01.png`,
        name: 'NIKE_PEGASUS_01.png',
        originalname: 'NIKE_PEGASUS_01.png',
      },
    ],
    content: `겨울용 디자인의 페가수스 트레일 5와 함께라면 비 오는 날의 트레일 러닝도 걱정 없습니다. 생활 방수 GORE-TEX 갑피, 전지형 밑창, 반사 디테일이 악천후에도 편안한 착화감을 선사합니다. 리액트X 폼 중창이 반응성이 뛰어난 쿠셔닝을 제공하기 때문에 활력 있게 달릴 수 있습니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC02', 'PC0201'], // Women > 신발
      primeCost: 209000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 209000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 페가수스 트레일 5 GORE-TEX',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_PEGASUS_01.png`,
        name: 'NIKE_PEGASUS_01.png',
        originalname: 'NIKE_PEGASUS_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_02.png`,
        name: 'NIKE_PEGASUS_02.png',
        originalname: 'NIKE_PEGASUS_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_03.png`,
        name: 'NIKE_PEGASUS_03.png',
        originalname: 'NIKE_PEGASUS_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_04.png`,
        name: 'NIKE_PEGASUS_04.png',
        originalname: 'NIKE_PEGASUS_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_05.png`,
        name: 'NIKE_PEGASUS_05.png',
        originalname: 'NIKE_PEGASUS_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_06.png`,
        name: 'NIKE_PEGASUS_06.png',
        originalname: 'NIKE_PEGASUS_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_07.jpeg`,
        name: 'NIKE_PEGASUS_07.jpeg',
        originalname: 'NIKE_PEGASUS_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_08.jpeg`,
        name: 'NIKE_PEGASUS_08.jpeg',
        originalname: 'NIKE_PEGASUS_08.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_09.png`,
        name: 'NIKE_PEGASUS_09.png',
        originalname: 'NIKE_PEGASUS_09.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_10.jpeg`,
        name: 'NIKE_PEGASUS_10.jpeg',
        originalname: 'NIKE_PEGASUS_10.jpeg',
      },
    ],
    content: `나이키 페가수스 트레일 5 GORE-TEX 검은색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '블랙/앤트러사이트/블랙',
      styleNo: 'FQ0912-002',
      primeCost: 209000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 209000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 페가수스 트레일 5 GORE-TEX',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_01.png`,
        name: 'NIKE_PEGASUS_b_01.png',
        originalname: 'NIKE_PEGASUS_b_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_02.png`,
        name: 'NIKE_PEGASUS_b_02.png',
        originalname: 'NIKE_PEGASUS_b_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_03.png`,
        name: 'NIKE_PEGASUS_b_03.png',
        originalname: 'NIKE_PEGASUS_b_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_04.png`,
        name: 'NIKE_PEGASUS_b_04.png',
        originalname: 'NIKE_PEGASUS_b_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_05.png`,
        name: 'NIKE_PEGASUS_b_05.png',
        originalname: 'NIKE_PEGASUS_b_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_06.png`,
        name: 'NIKE_PEGASUS_b_06.png',
        originalname: 'NIKE_PEGASUS_b_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_07.png`,
        name: 'NIKE_PEGASUS_b_07.png',
        originalname: 'NIKE_PEGASUS_b_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_08.png`,
        name: 'NIKE_PEGASUS_b_08.png',
        originalname: 'NIKE_PEGASUS_b_08.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_b_09.png`,
        name: 'NIKE_PEGASUS_b_09.png',
        originalname: 'NIKE_PEGASUS_b_09.png',
      },
    ],
    content: `나이키 페가수스 트레일 5 GORE-TEX 라임색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '샌드드리프트/사이버/라이프 라임/다크 포니',
      styleNo: 'FQ0912-101',
      primeCost: 209000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 209000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 페가수스 트레일 5 GORE-TEX',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_01.jpeg`,
        name: 'NIKE_PEGASUS_c_01.jpeg',
        originalname: 'NIKE_PEGASUS_c_01.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_02.png`,
        name: 'NIKE_PEGASUS_c_02.png',
        originalname: 'NIKE_PEGASUS_c_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_03.png`,
        name: 'NIKE_PEGASUS_c_03.png',
        originalname: 'NIKE_PEGASUS_c_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_04.jpeg`,
        name: 'NIKE_PEGASUS_c_04.jpeg',
        originalname: 'NIKE_PEGASUS_c_04.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_05.png`,
        name: 'NIKE_PEGASUS_c_05.png',
        originalname: 'NIKE_PEGASUS_c_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_06.png`,
        name: 'NIKE_PEGASUS_c_06.png',
        originalname: 'NIKE_PEGASUS_c_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_07.jpeg`,
        name: 'NIKE_PEGASUS_c_07.jpeg',
        originalname: 'NIKE_PEGASUS_c_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_PEGASUS_c_08.png`,
        name: 'NIKE_PEGASUS_c_08.png',
        originalname: 'NIKE_PEGASUS_c_08.png',
      },
    ],
    content: `나이키 페가수스 트레일 5 GORE-TEX 남색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '아머리 네이비/빈티지 그린/플래티넘 바이올렛/아머리 네이비',
      styleNo: 'FQ0912-400',
      primeCost: 209000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 119000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 필드 제너럴',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_01.png`,
        name: 'NIKE_FIELD_GENERAL_01.png',
        originalname: 'NIKE_FIELD_GENERAL_01.png',
      },
    ],
    content: `투지 넘치는 미식축구 문화에 뿌리를 둔 필드 제너럴이 돌아와 스니커즈계를 뒤흔듭니다. 인조 가죽과 튼튼한 직물 소재에 돌기 형태의 와플 밑창이 어우러져 빈티지한 그리드아이언 룩을 연출합니다. 스니커즈의 역사와 함께하며 미래로 나아가는 나만의 길을 개척해 보세요.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC02', 'PC0201'], // Women > 신발
      primeCost: 119000,
      gender: 'women',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 119000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 필드 제너럴',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_01.png`,
        name: 'NIKE_FIELD_GENERAL_01.png',
        originalname: 'NIKE_FIELD_GENERAL_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_02.png`,
        name: 'NIKE_FIELD_GENERAL_02.png',
        originalname: 'NIKE_FIELD_GENERAL_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_03.png`,
        name: 'NIKE_FIELD_GENERAL_03.png',
        originalname: 'NIKE_FIELD_GENERAL_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_04.png`,
        name: 'NIKE_FIELD_GENERAL_04.png',
        originalname: 'NIKE_FIELD_GENERAL_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_05.png`,
        name: 'NIKE_FIELD_GENERAL_05.png',
        originalname: 'NIKE_FIELD_GENERAL_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_06.png`,
        name: 'NIKE_FIELD_GENERAL_06.png',
        originalname: 'NIKE_FIELD_GENERAL_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_07.png`,
        name: 'NIKE_FIELD_GENERAL_07.png',
        originalname: 'NIKE_FIELD_GENERAL_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_08.png`,
        name: 'NIKE_FIELD_GENERAL_08.png',
        originalname: 'NIKE_FIELD_GENERAL_08.png',
      },
    ],
    content: `나이키 필드 제너럴 검은색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '블랙/블랙/메탈릭 실버',
      styleNo: 'FZ5593-001',
      primeCost: 119000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 119000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 필드 제너럴',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_01.png`,
        name: 'NIKE_FIELD_GENERAL_b_01.png',
        originalname: 'NIKE_FIELD_GENERAL_b_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_02.png`,
        name: 'NIKE_FIELD_GENERAL_b_02.png',
        originalname: 'NIKE_FIELD_GENERAL_b_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_03.png`,
        name: 'NIKE_FIELD_GENERAL_b_03.png',
        originalname: 'NIKE_FIELD_GENERAL_b_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_04.png`,
        name: 'NIKE_FIELD_GENERAL_b_04.png',
        originalname: 'NIKE_FIELD_GENERAL_b_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_05.png`,
        name: 'NIKE_FIELD_GENERAL_b_05.png',
        originalname: 'NIKE_FIELD_GENERAL_b_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_06.png`,
        name: 'NIKE_FIELD_GENERAL_b_06.png',
        originalname: 'NIKE_FIELD_GENERAL_b_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_07.png`,
        name: 'NIKE_FIELD_GENERAL_b_07.png',
        originalname: 'NIKE_FIELD_GENERAL_b_07.png',
      },
      {
        path: `/files/${clientId}/NIKE_FIELD_GENERAL_b_08.png`,
        name: 'NIKE_FIELD_GENERAL_b_08.png',
        originalname: 'NIKE_FIELD_GENERAL_b_08.png',
      },
    ],
    content: `나이키 필드 제너럴 핑크색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [220, 225, 230, 235, 240, 245, 250, 255, 260],
      color: '엘리멘탈 핑크/검 미디엄 브라운/옵시디언',
      styleNo: ' FZ5593-600',
      primeCost: 119000,
    },
  },
];
