{
_id: await nextSeq('product'),
        seller_id: 2,
        price: 169000,
        show: true,
        active: true,
        name: "나이키 에어 포스 1 '07 WB",
        quantity: 9999,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_01.png`,
            name: 'NIKE_AIR_FORCE_wb_01.png',
            originalname: 'NIKE_AIR_FORCE_wb_01.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_02.png`,
            name: 'NIKE_AIR_FORCE_wb_02.png',
            originalname: 'NIKE_AIR_FORCE_wb_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_03.png`,
            name: 'NIKE_AIR_FORCE_wb_03.png',
            originalname: 'NIKE_AIR_FORCE_wb_03.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_04.png`,
            name: 'NIKE_AIR_FORCE_wb_04.png',
            originalname: 'NIKE_AIR_FORCE_wb_04.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_05.png`,
            name: 'NIKE_AIR_FORCE_wb_05.png',
            originalname: 'NIKE_AIR_FORCE_wb_05.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_06.png`,
            name: 'NIKE_AIR_FORCE_wb_06.png',
            originalname: 'NIKE_AIR_FORCE_wb_06.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_07.jpeg`,
            name: 'NIKE_AIR_FORCE_wb_07.jpeg',
            originalname: 'NIKE_AIR_FORCE_wb_07.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_FORCE_wb_08.jpeg`,
            name: 'NIKE_AIR_FORCE_wb_08.jpeg',
            originalname: 'NIKE_AIR_FORCE_wb_08.jpeg',
          },
        ],
        content: `나이키 에어 포스 1 '07 WB로 전설을 이어갑니다. 로우컷으로 재탄생한 아이콘 AF1이 클래식한 코트 스타일과 프리미엄 쿠셔닝을 선사합니다..`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isNew: false,
          isBest: true,
          category: ['PC02', 'PC0201'], // Men > 신발
          size: [
            230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
            295, 300, 305, 310,
          ],
          color: '플랙스/검 라이트 브라운/블랙/휘트',
          styleNo: 'CJ9179-200',
          primeCost: 169000,
          gender: 'men',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 209000,
        show: true,
        active: true,
        name: '나이키 줌 보메로 롬',
        quantity: 9999,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_01.png`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_01.png',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_01.png',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_02.png`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_02.png',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_03.png`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_03.png',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_03.png',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_04.jpeg`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_04.jpeg',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_04.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_05.png`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_05.png',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_05.png',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_06.png`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_06.png',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_06.png',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_07.jpeg`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_07.jpeg',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_07.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_08.png`,
            name: 'NIKE_ZOOM_VOMERO_ROAM_08.png',
            originalname: 'NIKE_ZOOM_VOMERO_ROAM_08.png',
          },
        ],
        content: `도시 환경에 적합하도록 디자인된 이 겨울용 버전 보메로는 비 오는 날씨에 신기 좋습니다. 내구성 좋은 소재에 고무 머드가드가 결합되어 흙이나 물웅덩이로부터 신발을 보호해 줍니다. 또한 두툼한 중창이 어디를 걷더라도 눈에 띄는 편안함과 스타일을 선사합니다.`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isNew: false,
          isBest: true,
          category: ['PC02', 'PC0201'], // Men > 용품
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
            305, 310,
          ],
          color: '레이서 블루/서밋 화이트/블랙/레이서 블루',
          styleNo: 'FV2295-400',
          primeCost: 209000,
          gender: 'men',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 111200,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 덩크 로우 레트로',
        quantity: 9999,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_01.png`,
            name: 'NIKE_DUNK_LOW_RETRO_01.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_01.png',
          },
        ],
        content: `하드우드를 위해 태어나 스트리트로 무대를 옮겨온 나이키 덩크 로우 레트로가 산뜻한 오버레이와 오리지널 팀 컬러로 돌아왔습니다. 신을수록 부드러워지는 멋진 룩의 프리미엄 가죽 갑피가 특징인 이 농구 아이콘은 80년대 분위기를 한껏 발산합니다. 여기에 현대의 풋웨어 기술로 21세기의 편안함을 구현했습니다.`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 1,
          isNew: false,
          isBest: false,
          category: ['PC01', 'PC0201'], // Women > 신발
          primeCost: 139000,
          gender: 'men',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 111200,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 덩크 로우 레트로',
        quantity: 20,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_01.png`,
            name: 'NIKE_DUNK_LOW_RETRO_01.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_01.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_02.png`,
            name: 'NIKE_DUNK_LOW_RETRO_02.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_03.png`,
            name: 'NIKE_DUNK_LOW_RETRO_03.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_03.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_04.png`,
            name: 'NIKE_DUNK_LOW_RETRO_04.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_04.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_05.png`,
            name: 'NIKE_DUNK_LOW_RETRO_05.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_05.png',
          },
        ],
        content: `나이키 덩크 로우 레트로 검은색`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 2,
          parent: 1,
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
            305, 310,
          ],
          color: '화이트/화이트/블랙',
          styleNo: 'DD1391-100',
          primeCost: 139000,
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 139000,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 덩크 로우 레트로',
        quantity: 20,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_01.jpeg`,
            name: 'NIKE_DUNK_LOW_RETRO_g_01.jpeg',
            originalname: 'NIKE_DUNK_LOW_RETRO_g_01.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_02.png`,
            name: 'NIKE_DUNK_LOW_RETRO_g_02.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_g_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_03.jpeg`,
            name: 'NIKE_DUNK_LOW_RETRO_g_03.jpeg',
            originalname: 'NIKE_DUNK_LOW_RETRO_g_03.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_04.png`,
            name: 'NIKE_DUNK_LOW_RETRO_g_04.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_g_04.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_05.png`,
            name: 'NIKE_DUNK_LOW_RETRO_g_05.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_g_05.png',
          },
        ],
        content: `나이키 덩크 로우 레트로 녹색`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 2,
          parent: 1,
          size: [
            230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
            295, 300, 305, 310,
          ],
          color: '화이트/화이트/토탈 오렌지/팀 그린',
          styleNo: 'DD1391-101',
          primeCost: 139000,
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 111200,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 덩크 로우 레트로',
        quantity: 20,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_01.png`,
            name: 'NIKE_DUNK_LOW_RETRO_w_01.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_w_01.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_02.png`,
            name: 'NIKE_DUNK_LOW_RETRO_w_02.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_w_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_03.png`,
            name: 'NIKE_DUNK_LOW_RETRO_w_03.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_w_03.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_04.png`,
            name: 'NIKE_DUNK_LOW_RETRO_w_04.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_w_04.png',
          },
          {
            path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_05.png`,
            name: 'NIKE_DUNK_LOW_RETRO_w_05.png',
            originalname: 'NIKE_DUNK_LOW_RETRO_w_05.png',
          },
        ],
        content: `나이키 덩크 로우 레트로 흰색`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 2,
          parent: 1,
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
            305, 310,
          ],
          color: '화이트/그레이 포그',
          styleNo: 'DD1391-103',
          primeCost: 139000,
        },
      },

      {
_id: await nextSeq('product'),
        seller_id: 2,
        price: 129000,
        show: true,
        active: true,
        name: "나이키 P-6000",
        quantity: 9999,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_P_6000_01.jpeg`,
            name: 'NIKE_P_6000_01.jpeg',
            originalname: 'NIKE_P_6000_01.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_P-6000_02.png`,
            name: 'NIKE_P-6000_02.png',
            originalname: 'NIKE_P-6000_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_P-6000_03.jpeg`,
            name: 'NIKE_P-6000_03.jpeg',
            originalname: 'NIKE_P-6000_03.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_P-6000_04.jpeg`,
            name: 'NIKE_P-6000_04.jpeg',
            originalname: 'NIKE_P-6000_04.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_P-6000_05.png`,
            name: 'NIKE_P-6000_05.png',
            originalname: 'NIKE_P-6000_05.png',
          },
        ],
        content: `P-6000은 과거 페가수스 스니커즈를 매시업한 디자인이 특징으로, 2000년대 초의 러닝화 감성을 현대적으로 업그레이드했습니다. 통기성 좋은 메쉬와 스포티한 라인이 특징이며, 시선을 사로잡는 룩과 우수한 통기성 및 편안함이 완벽한 조화를 이룹니다. 아래에는 폼 쿠셔닝을 적용해 트랙에서 영감을 받은 높은 실루엣과 놀라운 쿠셔닝을 선사합니다.`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isNew: false,
          isBest: false,
          category: ['PC02', 'PC0201'], // Men > 신발
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
            295, 300, 305, 310,
          ],
          color: '카키/메탈릭 플래티넘/퓨어 플래티넘/메탈릭 실버',
          styleNo: 'HQ3030-200',
          primeCost: 129000,
          gender: 'men',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 169000,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 에어맥스 1 에센셜',
        quantity: 9999,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_01.png`,
            name: 'NIKE_AIR_MAX_1_ESS_01.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_01.png',
          },
        ],
        content: `무리를 이끄는 리더를 만나 보세요. 시끄러운 소음 너머, 구름 위를 걷는 듯한 느낌을 주는 에어맥스 1은 유행을 타지 않는 디자인과 편안한 쿠셔닝을 조합했습니다. 맥스 에어 유닛과 혼합 소재가 특징인 이 아이콘은 1987년에 처음 등장한 이후 오늘날까지 프랜차이즈의 영혼으로 자리매김하고 있습니다.`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 1,
          isNew: false,
          isBest: false,
          category: ['PC01', 'PC0201'], // Women > 신발
          primeCost: 169000,
          gender: 'men',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 169000,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 에어맥스 1 에센셜',
        quantity: 20,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_01.png`,
            name: 'NIKE_AIR_MAX_1_ESS_01.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_01.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_02.png`,
            name: 'NIKE_AIR_MAX_1_ESS_02.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_03.png`,
            name: 'NIKE_AIR_MAX_1_ESS_03.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_03.png',
          },
        ],
        content: `나이키 에어맥스 1 에센셜 분홍색`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 2,
          parent: 1,
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
            305, 310,
          ],
          color: '서밋 화이트/울프 그레이/화이트/다크 스모크 그레이',
          styleNo: 'FZ5808-104',
          primeCost: 169000,
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 169000,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 에어맥스 1 에센셜',
        quantity: 20,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_y_01.png`,
            name: 'NIKE_AIR_MAX_1_ESS_y_01.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_y_01.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_y_02.png`,
            name: 'NIKE_AIR_MAX_1_ESS_y_02.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_y_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_y_03.png`,
            name: 'NIKE_AIR_MAX_1_ESS_y_03.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_y_03.png',
          },
        ],
        content: `나이키 에어맥스 1 에센셜 노랑색`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 2,
          parent: 1,
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
            305, 310,
          ],
          color: '화이트/퓨어 플래티넘/블랙/유니버시티 골드',
          styleNo: 'FZ5808-100',
          primeCost: 169000,
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 169000,
        shippingFees: 3000,
        show: true,
        active: true,
        name: '나이키 에어맥스 1 에센셜',
        quantity: 20,
        buyQuantity: 10,
        mainImages: [
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_b_01.jpeg`,
            name: 'NIKE_AIR_MAX_1_ESS_b_01.jpeg',
            originalname: 'NIKE_AIR_MAX_1_ESS_b_01.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_b_02.png`,
            name: 'NIKE_AIR_MAX_1_ESS_b_02.png',
            originalname: 'NIKE_AIR_MAX_1_ESS_b_02.png',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_b_03.jpeg`,
            name: 'NIKE_AIR_MAX_1_ESS_b_03.jpeg',
            originalname: 'NIKE_AIR_MAX_1_ESS_b_03.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_b_04.jpeg`,
            name: 'NIKE_AIR_MAX_1_ESS_b_04.jpeg',
            originalname: 'NIKE_AIR_MAX_1_ESS_b_04.jpeg',
          },
          {
            path: `/files/${clientId}/NIKE_AIR_MAX_1_ESS_b_05.jpeg`,
            name: 'NIKE_AIR_MAX_1_ESS_b_05.jpeg',
            originalname: 'NIKE_AIR_MAX_1_ESS_b_05.jpeg',
          },
        ],
        content: `나이키 에어맥스 1 에센셜 파랑색`,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          depth: 2,
          parent: 1,
          size: [
            240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
          ],
          color: '스모크 그레이/울프 그레이/옵시디언/레이서 블루',
          styleNo: 'FZ5808-003',
          primeCost: 169000,
        },
      },
      {
        _id: await nextSeq('product'),
                seller_id: 2,
                price: 169000,
                show: true,
                active: true,
                name: "나이키 페가수스 41 프리미엄",
                quantity: 9999,
                buyQuantity: 0,
                mainImages: [
                  {
                    path: `/files/${clientId}/AIR_ZOOM_PEGASUS_41_PRM_01.png`,
                    name: 'AIR_ZOOM_PEGASUS_41_PRM_01.png',
                    originalname: 'AIR_ZOOM_PEGASUS_41_PRM_01.png',
                  },
                  {
                    path: `/files/${clientId}/AIR_ZOOM_PEGASUS_41_PRM_02.png`,
                    name: 'AIR_ZOOM_PEGASUS_41_PRM_02.png',
                    originalname: 'AIR_ZOOM_PEGASUS_41_PRM_02.png',
                  },
                  {
                    path: `/files/${clientId}/AIR_ZOOM_PEGASUS_41_PRM_03.png`,
                    name: 'AIR_ZOOM_PEGASUS_41_PRM_03.png',
                    originalname: 'AIR_ZOOM_PEGASUS_41_PRM_03.png',
                  },
                  {
                    path: `/files/${clientId}/AIR_ZOOM_PEGASUS_41_PRM_04.jpeg`,
                    name: 'AIR_ZOOM_PEGASUS_41_PRM_04.jpeg',
                    originalname: 'AIR_ZOOM_PEGASUS_41_PRM_04.jpeg',
                  },
                  {
                    path: `/files/${clientId}/AIR_ZOOM_PEGASUS_41_PRM_05.jpeg`,
                    name: 'AIR_ZOOM_PEGASUS_41_PRM_05.jpeg',
                    originalname: 'AIR_ZOOM_PEGASUS_41_PRM_05.jpeg',
                  },
                ],
                content: `겨울용 페가수스의 반응성 좋은 쿠셔닝은 낮이든 밤이든 상관없이 로드 러닝을 더욱 활력 있게 만들어 줍니다. 듀얼 에어 줌 유닛과 리액트X 폼 중창이 결합되어 가벼우면서도 탁월한 에너지 반환력을 느낄 수 있으며, 중창부터 갑피까지 적용된 반사 페인트는 발걸음에 빛을 더해줍니다.`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  isNew: false,
                  isBest: false,
                  category: ['PC02', 'PC0201'], // Men > 신발
                  size: [
                    240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
                    295, 300, 305, 310,
                  ],
                  color: '하이퍼 크림슨/세이프티 오렌지/포톤 더스트/메탈릭 실버',
                  styleNo: 'HQ2938-800',
                  primeCost: 129000,
                  gender: 'men',
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 189000,
                show: true,
                active: true,
                name: '나이키 줌 보메로 5',
                quantity: 9999,
                buyQuantity: 10,
                mainImages: [
                  {
                    path: `/files/${clientId}/NIKE_ZOOM_VOMERO_5_01.png`,
                    name: 'NIKE_ZOOM_VOMERO_5_01.png',
                    originalname: 'NIKE_ZOOM_VOMERO_5_01.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_ZOOM_VOMERO_5_02.png`,
                    name: 'NIKE_ZOOM_VOMERO_5_02.png',
                    originalname: 'NIKE_ZOOM_VOMERO_5_02.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_ZOOM_VOMERO_5_03.png`,
                    name: 'NIKE_ZOOM_VOMERO_5_03.png',
                    originalname: 'NIKE_ZOOM_VOMERO_5_03.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_ZOOM_VOMERO_5_04.jpeg`,
                    name: 'NIKE_ZOOM_VOMERO_5_04.jpeg',
                    originalname: 'NIKE_ZOOM_VOMERO_5_04.jpeg',
                  },
                  {
                    path: `/files/${clientId}/NIKE_ZOOM_VOMERO_5_05.png`,
                    name: 'NIKE_ZOOM_VOMERO_5_05.png',
                    originalname: 'NIKE_ZOOM_VOMERO_5_05.png',
                  },
                ],
                content: `줌 보메로 5와 함께 나만을 위한 새로운 길을 개척하세요. 복잡성과 깊이를 선사하며 더욱 쉽게 스타일링할 수 있습니다. 풍부한 레이어드 디자인에 직물과 가죽, 플라스틱 액센트가 더해져 이번 시즌 가장 멋진 스니커즈가 탄생했습니다.`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  isNew: false,
                  isBest: true,
                  category: ['PC02', 'PC0201'], // Men > 용품
                  size: [
                    240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
                    305, 310,
                  ],
                  color: '블랙/앤트러사이트/메탈릭 다크 그레이/블랙',
                  styleNo: 'HF1553-001',
                  primeCost: 189000,
                  gender: 'men',
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 112000,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키 프리 메트콘 6',
                quantity: 9999,
                buyQuantity: 0,
                mainImages: [
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_01.png`,
                    name: 'NIKE_FREE_METCON_6_01.png',
                    originalname: 'NIKE_FREE_METCON_6_01.png',
                  },
                ],
                content: `파워 리프트에서 사다리까지, 잔디밭에서 표면이 거친 플랫폼까지, 인조 구장에서 트랙까지. 모든 운동에는 특정한 목적과 집중하는 바가 있습니다. 프리 메트콘 6를 신으면 어떤 운동도 수월하게 하여 성과를 얻을 수 있습니다. 나이키에서 적응력이 가장 뛰어난 트레이너화에 앞꿈치 유연성을 좀 더 더하고 추가 폼으로 뒤꿈치를 보강했습니다. 덕분에 폴리오메트릭과 유산소 운동 중에 역동적인 움직임을 자유롭게 구사할 뿐 아니라 웨이트 트레이닝에 필요한 안정적인 베이스를 확보할 수 있죠.`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 1,
                  isNew: false,
                  isBest: false,
                  category: ['PC01', 'PC0201'], // Women > 신발
                  primeCost: 139000,
                  gender: 'men',
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 112000,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키 프리 메트콘 6',
                quantity: 20,
                buyQuantity: 10,
                mainImages: [
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_01.png`,
                    name: 'NIKE_FREE_METCON_6_01.png',
                    originalname: 'NIKE_FREE_METCON_6_01.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_02.png`,
                    name: 'NIKE_FREE_METCON_6_02.png',
                    originalname: 'NIKE_FREE_METCON_6_02.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_03.png`,
                    name: 'NIKE_FREE_METCON_6_03.png',
                    originalname: 'NIKE_FREE_METCON_6_03.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_04.jpeg`,
                    name: 'NIKE_FREE_METCON_6_04.jpeg',
                    originalname: 'NIKE_FREE_METCON_6_04.jpeg',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_05.png`,
                    name: 'NIKE_FREE_METCON_6_05.png',
                    originalname: 'NIKE_FREE_METCON_6_05.png',
                  },
                ],
                content: `나이키 프리 메트콘 6 검은색`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 2,
                  parent: 1,
                  size: [
                    240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
                    305, 310,
                  ],
                  color: '블랙/화이트',
                  styleNo: 'FJ7127-001',
                  primeCost: 139000,
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 112000,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키 프리 메트콘 6',
                quantity: 20,
                buyQuantity: 10,
                mainImages: [
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_b_01.jpeg`,
                    name: 'NIKE_FREE_METCON_6_b_01.jpeg',
                    originalname: 'NIKE_FREE_METCON_6_b_01.jpeg',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_b_02.png`,
                    name: 'NIKE_FREE_METCON_6_b_02.png',
                    originalname: 'NIKE_FREE_METCON_6_b_02.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_b_03.jpeg`,
                    name: 'NIKE_FREE_METCON_6_b_03.jpeg',
                    originalname: 'NIKE_FREE_METCON_6_b_03.jpeg',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_b_04.jpeg`,
                    name: 'NIKE_FREE_METCON_6_b_04.jpeg',
                    originalname: 'NIKE_FREE_METCON_6_b_04.jpeg',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_b_05.jpeg`,
                    name: 'NIKE_FREE_METCON_6_b_05.jpeg',
                    originalname: 'NIKE_FREE_METCON_6_b_05.jpeg',
                  },
                ],
                content: `나이키 프리 메트콘 6 파랑색`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 2,
                  parent: 1,
                  size: [ 
                    245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
                    305,
                  ],
                  color: '애스트로너미 블루/하이퍼 크림슨/페일 아이보리/블랙',
                  styleNo: 'FJ7127-401',
                  primeCost: 139000,
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 139000,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키 프리 메트콘 6',
                quantity: 20,
                buyQuantity: 10,
                mainImages: [
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_w_01.png`,
                    name: 'NIKE_FREE_METCON_6_w_01.png',
                    originalname: 'NIKE_FREE_METCON_6_w_01.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_w_02.png`,
                    name: 'NIKE_FREE_METCON_6_w_02.png',
                    originalname: 'NIKE_FREE_METCON_6_w_02.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_w_03.png`,
                    name: 'NIKE_FREE_METCON_6_w_03.png',
                    originalname: 'NIKE_FREE_METCON_6_w_03.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_w_04.png`,
                    name: 'NIKE_FREE_METCON_6_w_04.png',
                    originalname: 'NIKE_FREE_METCON_6_w_04.png',
                  },
                  {
                    path: `/files/${clientId}/NIKE_FREE_METCON_6_w_05.png`,
                    name: 'NIKE_FREE_METCON_6_w_05.png',
                    originalname: 'NIKE_FREE_METCON_6_w_05.png',
                  },
                ],
                content: `나이키 프리 메트콘 6 흰색`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 2,
                  parent: 1,
                  size: [ 
                    250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
                  ],
                  color: '화이트/화이트/볼트',
                  styleNo: 'FJ7127-104',
                  primeCost: 139000,
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 71200,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키코트 라이트 4',
                quantity: 9999,
                buyQuantity: 0,
                mainImages: [
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_01.png`,
                    name: 'M_NIKE_COURT_LITE_4_01.png',
                    originalname: 'M_NIKE_COURT_LITE_4_01.png',
                  },
                ],
                content: `나이키코트 라이트 4는 디깅 또는 딩킹 동작을 하거나 스플릿 세트에서 스크램블링 후 공을 라인 아래로 보낼 때 서브를 지속하는 데 도움을 줍니다. 내구성이 좋으면서도 긴 랠리 중에도 활동성을 선사하므로 근거리든 원거리든 받아칠 수 없는 샷을 날리기에 이상적입니다.`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 1,
                  isNew: false,
                  isBest: false,
                  category: ['PC01', 'PC0201'], // Women > 신발
                  primeCost: 89000,
                  gender: 'men',
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 72000,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키코트 라이트 4',
                quantity: 20,
                buyQuantity: 10,
                mainImages: [
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_01.png`,
                    name: 'M_NIKE_COURT_LITE_4_01.png',
                    originalname: 'M_NIKE_COURT_LITE_4_01.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_02.png`,
                    name: 'M_NIKE_COURT_LITE_4_02.png',
                    originalname: 'M_NIKE_COURT_LITE_4_02.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_03.png`,
                    name: 'M_NIKE_COURT_LITE_4_03.png',
                    originalname: 'M_NIKE_COURT_LITE_4_03.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_04.png`,
                    name: 'M_NIKE_COURT_LITE_4_04.png',
                    originalname: 'M_NIKE_COURT_LITE_4_04.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_05.png    `,
                    name: 'M_NIKE_COURT_LITE_4_05.png   ',
                    originalname: 'M_NIKE_COURT_LITE_4_05.png   ',
                  },
                ],
                content: `나이키 프리 메트콘 6 흰색`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 2,
                  parent: 1,
                  size: [
                    240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
                    305, 310,
                  ],
                  color: '화이트/서밋 화이트/블랙',
                  styleNo: 'FD6574-100',
                  primeCost: 89000,
                },
              },
              {
                _id: await nextSeq('product'),
                seller_id: 2,
                price: 80100,
                shippingFees: 3000,
                show: true,
                active: true,
                name: '나이키코트 라이트 4',
                quantity: 20,
                buyQuantity: 10,
                mainImages: [
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_m_01.png`,
                    name: 'M_NIKE_COURT_LITE_4_m_01.png',
                    originalname: 'M_NIKE_COURT_LITE_4_m_01.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_m_02.png`,
                    name: 'M_NIKE_COURT_LITE_4_m_02.png',
                    originalname: 'M_NIKE_COURT_LITE_4_m_02.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_m_03.png`,
                    name: 'M_NIKE_COURT_LITE_4_m_03.png',
                    originalname: 'M_NIKE_COURT_LITE_4_m_03.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_m_04.png`,
                    name: 'M_NIKE_COURT_LITE_4_m_04.png',
                    originalname: 'M_NIKE_COURT_LITE_4_m_04.png',
                  },
                  {
                    path: `/files/${clientId}/M_NIKE_COURT_LITE_4_m_05.png    `,
                    name: 'M_NIKE_COURT_LITE_4_m_05.png   ',
                    originalname: 'M_NIKE_COURT_LITE_4_m_05.png   ',
                  },
                ],
                content: `나이키 프리 메트콘 6 민트색`,
                createdAt: getTime(-41, -60 * 60 * 2),
                updatedAt: getTime(-40, -60 * 15),
                extra: {
                  depth: 2,
                  parent: 1,
                  size: [
                    240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300,
                    305, 310,
                  ],
                  color: '화이트/아머리 네이비/데님 터콰이즈/볼트',
                  styleNo: 'FD6574-101',
                  primeCost: 89000,
                },
              },
              {
                _id: await nextSeq('product'),
                        seller_id: 2,
                        price: 47200,
                        show: true,
                        active: true,
                        name: "나이키 캄",
                        quantity: 9999,
                        buyQuantity: 0,
                        mainImages: [
                          {
                            path: `/files/${clientId}/NIKE_CALM_SLIDE_01.png`,
                            name: 'NIKE_CALM_SLIDE_01.png',
                            originalname: 'NIKE_CALM_SLIDE_01.png',
                          },
                          {
                            path: `/files/${clientId}/NIKE_CALM_SLIDE_02.jpeg`,
                            name: 'NIKE_CALM_SLIDE_02.jpeg',
                            originalname: 'NIKE_CALM_SLIDE_02.jpeg',
                          },
                          {
                            path: `/files/${clientId}/NIKE_CALM_SLIDE_03.png`,
                            name: 'NIKE_CALM_SLIDE_03.png',
                            originalname: 'NIKE_CALM_SLIDE_03.png',
                          },
                          {
                            path: `/files/${clientId}/NIKE_CALM_SLIDE_04.png`,
                            name: 'NIKE_CALM_SLIDE_04.png',
                            originalname: 'NIKE_CALM_SLIDE_04.png',
                          },
                          {
                            path: `/files/${clientId}/NIKE_CALM_SLIDE_05.png`,
                            name: 'NIKE_CALM_SLIDE_05.png',
                            originalname: 'NIKE_CALM_SLIDE_05.png',
                          },
                        ],
                        content: `휴식하는 날 어디를 가든 차분하고 편안한 하루를 보낼 수 있습니다. 부드러우면서도 반응성이 좋은 폼으로 제작된 이 경량 슬라이드는 스타일링이 쉽고 휴대성이 뛰어납니다. 물놀이에 최적화된 디자인으로 해변이나 수영장에서 신기 좋을 뿐만 아니라, 미니멀한 룩이 도시에서 착용해도 어울릴 만큼 고급스러운 느낌을 선사합니다. 이 신발을 신고 직접 확인해 보세요.`,
                        createdAt: getTime(-41, -60 * 60 * 2),
                        updatedAt: getTime(-40, -60 * 15),
                        extra: {
                          isNew: false,
                          isBest: true,
                          category: ['PC02', 'PC0201'], // Men > 신발
                          size: [
                            230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
                            295, 300, 305, 310,
                          ],
                          color: '카키/카키',
                          styleNo: 'FD4116-201',
                          primeCost: 59000,
                          gender: 'men',
                        },
                      },