product: [
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 169000,
    show: true,
    active: true,
    name: "나이키 에어 포스 1 '07 WB",
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_01.png`,
        name: 'NIKE_AIR_FORCE_wb_01.png',
        originalname: 'NIKE_AIR_FORCE_wb_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_02.png`,
        name: 'NIKE_AIR_FORCE_wb_02.png',
        originalname: 'NIKE_AIR_FORCE_wb_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_03.png`,
        name: 'NIKE_AIR_FORCE_wb_03.png',
        originalname: 'NIKE_AIR_FORCE_wb_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_04.png`,
        name: 'NIKE_AIR_FORCE_wb_04.png',
        originalname: 'NIKE_AIR_FORCE_wb_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_05.png`,
        name: 'NIKE_AIR_FORCE_wb_05.png',
        originalname: 'NIKE_AIR_FORCE_wb_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_06.png`,
        name: 'NIKE_AIR_FORCE_wb_06.png',
        originalname: 'NIKE_AIR_FORCE_wb_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_07.jpeg`,
        name: 'NIKE_AIR_FORCE_wb_07.jpeg',
        originalname: 'NIKE_AIR_FORCE_wb_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_08.jpeg`,
        name: 'NIKE_AIR_FORCE_wb_08.jpeg',
        originalname: 'NIKE_AIR_FORCE_wb_08.jpeg',
      },
    ],
    content: `나이키 에어 포스 1 '07 WB로 전설을 이어갑니다. 로우컷으로 재탄생한 아이콘 AF1이 클래식한 코트 스타일과 프리미엄 쿠셔닝을 선사합니다..`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      isNew: false,
      isBest: true,
      category: ['PC02', 'PC0203'], // Women > 용품
      size: [
        230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295,
        300, 305, 310,
      ],
      color: '플랙스/검 라이트 브라운/블랙/휘트',
      styleNo: 'CJ9179-200',
      primeCost: 169000,
      gender: 'men',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 209000,
    show: true,
    active: true,
    name: '나이키 줌 보메로 롬',
    quantity: 9999,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_01.png`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_01.png',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_02.png`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_02.png',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_03.png`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_03.png',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_04.jpeg`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_04.jpeg',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_04.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_05.png`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_05.png',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_05.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_06.png`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_06.png',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_06.png',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_07.jpeg`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_07.jpeg',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_07.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_ZOOM_VOMERO_ROAM_08.png`,
        name: 'NIKE_ZOOM_VOMERO_ROAM_08.png',
        originalname: 'NIKE_ZOOM_VOMERO_ROAM_08.png',
      },
    ],
    content: `도시 환경에 적합하도록 디자인된 이 겨울용 버전 보메로는 비 오는 날씨에 신기 좋습니다. 내구성 좋은 소재에 고무 머드가드가 결합되어 흙이나 물웅덩이로부터 신발을 보호해 줍니다. 또한 두툼한 중창이 어디를 걷더라도 눈에 띄는 편안함과 스타일을 선사합니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      isNew: false,
      isBest: true,
      category: ['PC02', 'PC0203'], // Women > 용품
      size: [
        240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
        310,
      ],
      color: '레이서 블루/서밋 화이트/블랙/레이서 블루',
      styleNo: 'FV2295-400',
      primeCost: 209000,
      gender: 'men',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 209000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 줌 보메로 롬',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_AIR_FORCE_wb_01.png`,
        name: 'NIKE_AIR_FORCE_01.png',
        originalname: 'NIKE_AIR_FORCE_01.png',
      },
    ],
    content: `나이키 에어 포스 1 '07 WB로 전설을 이어갑니다. 로우컷으로 재탄생한 아이콘 AF1이 클래식한 코트 스타일과 프리미엄 쿠셔닝을 선사합니다..`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: true,
      isBest: false,
      category: ['PC01', 'PC0201'], // Women > 신발
      primeCost: 169000,
      gender: 'men',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 111200,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 덩크 로우 레트로',
    quantity: 9999,
    buyQuantity: 0,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_01.png`,
        name: 'NIKE_DUNK_LOW_RETRO_01.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_01.png',
      },
    ],
    content: `하드우드를 위해 태어나 스트리트로 무대를 옮겨온 나이키 덩크 로우 레트로가 산뜻한 오버레이와 오리지널 팀 컬러로 돌아왔습니다. 신을수록 부드러워지는 멋진 룩의 프리미엄 가죽 갑피가 특징인 이 농구 아이콘은 80년대 분위기를 한껏 발산합니다. 여기에 현대의 풋웨어 기술로 21세기의 편안함을 구현했습니다.`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 1,
      isNew: false,
      isBest: false,
      category: ['PC01', 'PC0201'], // Women > 신발
      primeCost: 139000,
      gender: 'men',
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 111200,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 덩크 로우 레트로',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_01.png`,
        name: 'NIKE_DUNK_LOW_RETRO_01.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_02.png`,
        name: 'NIKE_DUNK_LOW_RETRO_02.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_03.png`,
        name: 'NIKE_DUNK_LOW_RETRO_03.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_04.png`,
        name: 'NIKE_DUNK_LOW_RETRO_04.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_05.png`,
        name: 'NIKE_DUNK_LOW_RETRO_05.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_05.png',
      },
    ],
    content: `나이키 덩크 로우 레트로 검은색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [
        240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
        310,
      ],
      color: '화이트/화이트/블랙',
      styleNo: 'DD1391-100',
      primeCost: 139000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 139000,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 덩크 로우 레트로',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_01.jpeg`,
        name: 'NIKE_DUNK_LOW_RETRO_g_01.jpeg',
        originalname: 'NIKE_DUNK_LOW_RETRO_g_01.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_02.png`,
        name: 'NIKE_DUNK_LOW_RETRO_g_02.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_g_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_03.jpeg`,
        name: 'NIKE_DUNK_LOW_RETRO_g_03.jpeg',
        originalname: 'NIKE_DUNK_LOW_RETRO_g_03.jpeg',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_04.png`,
        name: 'NIKE_DUNK_LOW_RETRO_g_04.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_g_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_g_05.png`,
        name: 'NIKE_DUNK_LOW_RETRO_g_05.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_g_05.png',
      },
    ],
    content: `나이키 덩크 로우 레트로 녹색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [
        230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295,
        300, 305, 310,
      ],
      color: '화이트/화이트/토탈 오렌지/팀 그린',
      styleNo: 'DD1391-101',
      primeCost: 139000,
    },
  },
  {
    _id: await nextSeq('product'),
    seller_id: 2,
    price: 111200,
    shippingFees: 3000,
    show: true,
    active: true,
    name: '나이키 덩크 로우 레트로',
    quantity: 20,
    buyQuantity: 10,
    mainImages: [
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_01.png`,
        name: 'NIKE_DUNK_LOW_RETRO_w_01.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_w_01.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_02.png`,
        name: 'NIKE_DUNK_LOW_RETRO_w_02.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_w_02.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_03.png`,
        name: 'NIKE_DUNK_LOW_RETRO_w_03.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_w_03.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_04.png`,
        name: 'NIKE_DUNK_LOW_RETRO_w_04.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_w_04.png',
      },
      {
        path: `/files/${clientId}/NIKE_DUNK_LOW_RETRO_w_05.png`,
        name: 'NIKE_DUNK_LOW_RETRO_w_05.png',
        originalname: 'NIKE_DUNK_LOW_RETRO_w_05.png',
      },
    ],
    content: `나이키 덩크 로우 레트로 흰색`,
    createdAt: getTime(-41, -60 * 60 * 2),
    updatedAt: getTime(-40, -60 * 15),
    extra: {
      depth: 2,
      parent: 1,
      size: [
        240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
        310,
      ],
      color: '화이트/그레이 포그',
      styleNo: 'DD1391-103',
      primeCost: 139000,
    },
  },
];
